"""empty message

Revision ID: 4118dc392167
Revises: 6bc77ab9ee29
Create Date: 2021-02-19 09:42:19.468900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4118dc392167'
down_revision = '6bc77ab9ee29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whitelist_user_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['whitelist_group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['whitelist_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'whitelist_group', 'roles', ['role_id'], ['id'])
    op.drop_constraint(None, 'whitelist_user', type_='foreignkey')
    op.drop_column('whitelist_user', 'group_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('whitelist_user', sa.Column('group_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'whitelist_user', 'whitelist_group', ['group_id'], ['id'])
    op.drop_constraint(None, 'whitelist_group', type_='foreignkey')
    op.drop_table('whitelist_user_groups')
    # ### end Alembic commands ###
