"""empty message

Revision ID: 6bc77ab9ee29
Revises: e64c1982c0ae
Create Date: 2021-02-17 16:01:39.723083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bc77ab9ee29'
down_revision = 'e64c1982c0ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('whitelist_group', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'whitelist_group', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'whitelist_group', type_='foreignkey')
    op.drop_column('whitelist_group', 'role_id')
    # ### end Alembic commands ###
